const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";

export { ALERT, REFETCH_CHATS, NEW_MESSAGE,NEW_MESSAGE_ALERT, NEW_ATTACHMENT };
